%YAML:1.0

Camera.type: "PinHole"

Camera.fx: 675.73
Camera.fy: 722.76
Camera.cx: 1000.94
Camera.cy: 593.49

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0

Camera.width: 1920
Camera.height: 1200

Camera.fps: 30.0

Camera.bf: 67.573

Camera.RGB: 0

ThDepth: 40.0

ORBextractor.nFeatures: 1500
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500

Stereo.T_c1_c2: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [1.0, 0.0, 0.0, -0.10,   # baseline 10cm su X
          0.0, 1.0, 0.0,  0.0,
          0.0, 0.0, 1.0,  0.0,
          0.0, 0.0, 0.0,  1.0]

Stereo.ThDepth: 40.0
