%YAML:1.0

Camera.type: "PinHole"

Camera.fx: 225.24
Camera.fy: 240.92
Camera.cx: 333.65
Camera.cy: 197.83

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0

Camera.width: 640
Camera.height: 400
Camera.fps: 10
Camera.RGB: 0

Tbc: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [0.0, -1.0, 0.0, 0.00708,
          0.0, 0.0, -1.0, 0.00196,
          1.0, 0.0, 0.0, -0.00610,
          0.0, 0.0, 0.0, 1.0]

IMU.Frequency: 185
IMU.NoiseGyro: 0.0002   # [rad/s/sqrt(Hz)] (check your IMU datasheet)
IMU.NoiseAcc: 0.002     # [m/s^2/sqrt(Hz)] (check your IMU datasheet)
IMU.GyroWalk: 0.00002   # [rad/s^2/sqrt(Hz)]
IMU.AccWalk: 0.0002     # [m/s^3/sqrt(Hz)]
IMU.Tau: 0.005
IMU.Preintegration: true

ORBextractor.nFeatures: 2000
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 7
ORBextractor.minThFAST: 3

Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500
Viewer.minFrames: 0
Viewer.maxFrames: 30
